---
driver:
  name: vagrant

provisioner:
  name: chef_zero
<<<<<<< HEAD
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
=======
>>>>>>> before custom resource
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
<<<<<<< HEAD
  - name: ubuntu-16.04
=======
>>>>>>> before custom resource
  - name: centos-7.3
suites:
  - name: default
    run_list:
      - recipe[my_cookbook::default]
<<<<<<< HEAD
=======
  - name: with_role
    run_list:
      - role[my_cookbook_role]
  - name: with_calc_role
    run_list:
      - role[calculator_role]
>>>>>>> before custom resource
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
<<<<<<< HEAD
  - name: server
    run_list:
      - recipe[my_cookbook::server]
    varifier:
      inspec_test:
        - test/smoke/server
    attributes:
=======
>>>>>>> before custom resource
